/**
 *CityEnglishName.java[V 1.0.0]
 *classes : com.example.webservic_demo.CityEnglishName
 * 李志华 Create at 2014年7月10日 下午3:11:57
 */
package com.eric.xlee.weather;

import java.util.HashMap;
import java.util.Map;

/**
 * com.example.webservic_demo.CityEnglishName
 * 
 * @author 李志华 <br/>
 *         create at 2014年7月10日 下午3:11:57
 */
public class CityEnglishName {
    private static Map<String, String> CITY_ENGLISH_MAP = new HashMap<String, String>();
    static {
        CITY_ENGLISH_MAP.put("屯溪", "Tunki");
        CITY_ENGLISH_MAP.put("蚌埠", "Pengpu");
        CITY_ENGLISH_MAP.put("江苏", "Kiangsu");
        CITY_ENGLISH_MAP.put("南京", "Nanking");
        CITY_ENGLISH_MAP.put("苏州", "Soochow");
        CITY_ENGLISH_MAP.put("徐州", "Süchow");
        CITY_ENGLISH_MAP.put("海州", "Haichow");
        CITY_ENGLISH_MAP.put("浙江", "Chekiang");
        CITY_ENGLISH_MAP.put("杭州", "Hangchow");
        CITY_ENGLISH_MAP.put("台州", "Taichow");
        CITY_ENGLISH_MAP.put("宁波", "Ningpo");
        CITY_ENGLISH_MAP.put("温州", "Wenchow");
        CITY_ENGLISH_MAP.put("建瓯", "Kienow");
        CITY_ENGLISH_MAP.put("江西", "Kiangsi");
        CITY_ENGLISH_MAP.put("赣州", "Kanchow");
        CITY_ENGLISH_MAP.put("吉安", "Ki-an");
        CITY_ENGLISH_MAP.put("苏州", "Soochow");
        CITY_ENGLISH_MAP.put("黑龙江", "the Amur R.");
        CITY_ENGLISH_MAP.put("哈尔滨", "Harbin");
        CITY_ENGLISH_MAP.put("兴安府", "Hinganfu");
        CITY_ENGLISH_MAP.put("佳木斯", "Kiamusze");
        CITY_ENGLISH_MAP.put("齐齐哈尔", "Tsitsihar");
        CITY_ENGLISH_MAP.put("牡丹江", "Mutankiang");
        CITY_ENGLISH_MAP.put("吉林", "Kirin");
        CITY_ENGLISH_MAP.put("四平街", "Szepingkai");
        CITY_ENGLISH_MAP.put("延吉", "Yenki");
        CITY_ENGLISH_MAP.put("奉天", "Mukden");
        CITY_ENGLISH_MAP.put("营口", "Yingkow");
        CITY_ENGLISH_MAP.put("通化", "Tunghua");
        CITY_ENGLISH_MAP.put("山东", "Shangtung");
        CITY_ENGLISH_MAP.put("济南", "Tsinan");
        CITY_ENGLISH_MAP.put("青岛", "Tsingtao");
        CITY_ENGLISH_MAP.put("阳谷", "Yangku");
        CITY_ENGLISH_MAP.put("烟台", "Yentai");
        CITY_ENGLISH_MAP.put("兖州", "Yenchow");
        CITY_ENGLISH_MAP.put("周村", "Chowtsun");
        CITY_ENGLISH_MAP.put("临清", "Lintsing");
        CITY_ENGLISH_MAP.put("威海卫", "Weihaiwei");
        CITY_ENGLISH_MAP.put("曲阜", "Chufu");
        CITY_ENGLISH_MAP.put("沂州", "Ichow");
        CITY_ENGLISH_MAP.put("曹州", "Tsaochow");
        CITY_ENGLISH_MAP.put("河南", "Honan");
        CITY_ENGLISH_MAP.put("开封", "Kaifeng");
        CITY_ENGLISH_MAP.put("卫辉", "Weihwei");
        CITY_ENGLISH_MAP.put("洛阳", "Loyang");
        CITY_ENGLISH_MAP.put("信阳", "Sinyang");
        CITY_ENGLISH_MAP.put("归德", "Kweiteh");
        CITY_ENGLISH_MAP.put("郑州", "Chengchow");
        CITY_ENGLISH_MAP.put("深圳", "Shenzhen");
        CITY_ENGLISH_MAP.put("梅州", "Meizhou");
        CITY_ENGLISH_MAP.put("驻马店", "Chumatien");
        CITY_ENGLISH_MAP.put("新乡", "Sinsiang");
        CITY_ENGLISH_MAP.put("湖北", "Hupei");
        CITY_ENGLISH_MAP.put("汉口", "Hankow");
        CITY_ENGLISH_MAP.put("施南", "Shihnan");
        CITY_ENGLISH_MAP.put("老河口", "Laohokow");
        CITY_ENGLISH_MAP.put("莆圻", "Puchi");
        CITY_ENGLISH_MAP.put("宜昌", "Ichang");
        CITY_ENGLISH_MAP.put("蕲州", "Kichow");
        CITY_ENGLISH_MAP.put("襄阳", "Siangyang");
        CITY_ENGLISH_MAP.put("沙市", "Shasi");
        CITY_ENGLISH_MAP.put("随县", "Suihsien");
        CITY_ENGLISH_MAP.put("宜都", "Idu");
        CITY_ENGLISH_MAP.put("常德", "Changteh");
        CITY_ENGLISH_MAP.put("衡州", "Hengchow");
        CITY_ENGLISH_MAP.put("宁远", "Ningyüan");
        CITY_ENGLISH_MAP.put("沅陵州", "Yüanling");
        CITY_ENGLISH_MAP.put("保庆", "Paoking");
        CITY_ENGLISH_MAP.put("永州", "Yungchow");
        CITY_ENGLISH_MAP.put("澧州", "Lichow");
        CITY_ENGLISH_MAP.put("岳州", "Yochow");
        CITY_ENGLISH_MAP.put("湘潭", "Siangtan");
        CITY_ENGLISH_MAP.put("四川", "Szechuan");
        CITY_ENGLISH_MAP.put("成都", "Chengtu");
        CITY_ENGLISH_MAP.put("康定", "Kangting");
        CITY_ENGLISH_MAP.put("嘉定", "Kiating");
        CITY_ENGLISH_MAP.put("万县", "Wanhsien");
        CITY_ENGLISH_MAP.put("马尔康", "Barkan");
        CITY_ENGLISH_MAP.put("张家口", "Changkiakow");
        CITY_ENGLISH_MAP.put("北京", "Beijing");
        CITY_ENGLISH_MAP.put("天津", "Tientsin");
        CITY_ENGLISH_MAP.put("新疆", "Sinkiang");
        CITY_ENGLISH_MAP.put("乌鲁木齐", "ürümqi");
        CITY_ENGLISH_MAP.put("和田", "Hotan");
        CITY_ENGLISH_MAP.put("伊犁", "Ili");
        CITY_ENGLISH_MAP.put("克拉玛依", "Karamay");
        CITY_ENGLISH_MAP.put("吐鲁番", "Turpan");
        CITY_ENGLISH_MAP.put("哈密", "Kumul");
        CITY_ENGLISH_MAP.put("阿克苏", "Aksu");
        CITY_ENGLISH_MAP.put("喀什", "Kaxqar");
        CITY_ENGLISH_MAP.put("帕米尔", "Pamir");
        CITY_ENGLISH_MAP.put("塔里木", "Tarim");
        CITY_ENGLISH_MAP.put("塔克拉马干", "Taklimakan");
        CITY_ENGLISH_MAP.put("叶尔羌", "Yarkant");
        CITY_ENGLISH_MAP.put("罗布泊", "LopNur");
        CITY_ENGLISH_MAP.put("博斯腾", "Bosten");
        CITY_ENGLISH_MAP.put("轮台", "Bügür");
        CITY_ENGLISH_MAP.put("阿尔泰", "Altay");
        CITY_ENGLISH_MAP.put("车尔臣河", "Qarqan");
        CITY_ENGLISH_MAP.put("喀拉喀什河", "Karakax");
        CITY_ENGLISH_MAP.put("巴音郭楞", "Bayingolin");
        CITY_ENGLISH_MAP.put("额尔齐斯", "Ertix");
        CITY_ENGLISH_MAP.put("西藏", "Tibet");
        CITY_ENGLISH_MAP.put("拉萨", "Lhasa");
        CITY_ENGLISH_MAP.put("日喀则", "Xigazê");
        CITY_ENGLISH_MAP.put("雅鲁藏布江", "Yarlung Zangbo");
        CITY_ENGLISH_MAP.put("江孜", "Gyangzêê");
        CITY_ENGLISH_MAP.put("昌都", "Qamdo");
        CITY_ENGLISH_MAP.put("纳木错", "Namco");
        CITY_ENGLISH_MAP.put("喜马拉雅", "Himalaya");
        CITY_ENGLISH_MAP.put("珠穆朗玛", "Qomolangma");
        CITY_ENGLISH_MAP.put("唐古拉山", "Tanglha");
        CITY_ENGLISH_MAP.put("念青唐古拉山", "Nyanqêntanglha");
        CITY_ENGLISH_MAP.put("察隅", "Zayü");
        CITY_ENGLISH_MAP.put("青海", "Tsinghai");
        CITY_ENGLISH_MAP.put("西宁", "Sining");
        CITY_ENGLISH_MAP.put("内蒙古", "Inner Mongolia");
        CITY_ENGLISH_MAP.put("哈喇沁旗", "Harqin");
        CITY_ENGLISH_MAP.put("巴丹吉林沙漠", "Badan Jaran");
        CITY_ENGLISH_MAP.put("巴彦淖尔", "Bayan Nur");
        CITY_ENGLISH_MAP.put("阿拉善", "Alxa");
        CITY_ENGLISH_MAP.put("毛乌素沙漠", "Mu Us");
        CITY_ENGLISH_MAP.put("乌兰察布", "Ulan Qab");
        CITY_ENGLISH_MAP.put("腾格里", "Tengger");
        CITY_ENGLISH_MAP.put("土默特", "Tumd");
        CITY_ENGLISH_MAP.put("二连浩特", "Erenhot");
        CITY_ENGLISH_MAP.put("锡林郭楞", "Xilin Gol");
        CITY_ENGLISH_MAP.put("锡林浩特", "Xilinhot");
        CITY_ENGLISH_MAP.put("呼伦贝尔", "Hulun Buir");
        CITY_ENGLISH_MAP.put("鄂伦春", "Oroqen");
        CITY_ENGLISH_MAP.put("鄂温克", "Ewenki");
        CITY_ENGLISH_MAP.put("海拉尔", "Hailar");
        CITY_ENGLISH_MAP.put("集宁", "Tsining");
        CITY_ENGLISH_MAP.put("格尔木", "Golmud");
        CITY_ENGLISH_MAP.put("巴颜喀拉", "Bayanhar");
        CITY_ENGLISH_MAP.put("喀喇昆仑", "Karakorum");
        CITY_ENGLISH_MAP.put("可可西里", "Hoh Xil");
        CITY_ENGLISH_MAP.put("柴达木", "Qaidam");
        CITY_ENGLISH_MAP.put("察尔汗", "Qarham");
        CITY_ENGLISH_MAP.put("鄂陵湖", "Ngoring Hu");
        CITY_ENGLISH_MAP.put("扎陵湖", "Gyaring Hu");
        CITY_ENGLISH_MAP.put("满洲诸省", "Manchuria");
        CITY_ENGLISH_MAP.put("北安", "Pei’an");
        CITY_ENGLISH_MAP.put("兴安", "Hsingan");
        CITY_ENGLISH_MAP.put("嫩江", "Nunkiang");
        CITY_ENGLISH_MAP.put("松江", "Sungkiang");
        CITY_ENGLISH_MAP.put("合江", "Hokiang");
        CITY_ENGLISH_MAP.put("辽北", "Liaopei");
        CITY_ENGLISH_MAP.put("辽西", "Liaosi");
        CITY_ENGLISH_MAP.put("安东", "Antung");
        CITY_ENGLISH_MAP.put("察哈尔", "Chahar");
        CITY_ENGLISH_MAP.put("绥远", "Suiyüan");
        CITY_ENGLISH_MAP.put("热河", "Jehol");
        CITY_ENGLISH_MAP.put("西康", "Sikang");
        CITY_ENGLISH_MAP.put("安徽", "Anhwei");
        CITY_ENGLISH_MAP.put("安庆", "Anching");
        CITY_ENGLISH_MAP.put("锦州", "Chinchow");
        CITY_ENGLISH_MAP.put("安国", "Ankwo");
        CITY_ENGLISH_MAP.put("扬州", "Yangchow");
        CITY_ENGLISH_MAP.put("上海", "Shanghai");
        CITY_ENGLISH_MAP.put("重庆", "Chungking");
        CITY_ENGLISH_MAP.put("大连", "Dalny");
        CITY_ENGLISH_MAP.put("澳门", "Macau");
        CITY_ENGLISH_MAP.put("承德", "Chengteh");
        CITY_ENGLISH_MAP.put("秦皇岛", "Chinhwangtao");
        CITY_ENGLISH_MAP.put("沧州", "Tsangchow");
        CITY_ENGLISH_MAP.put("北海", "Beihai");
        CITY_ENGLISH_MAP.put("博白", "Pokpak");
        CITY_ENGLISH_MAP.put("韶关", "Shiukwan");
        CITY_ENGLISH_MAP.put("贵州", "Kweichow");
        CITY_ENGLISH_MAP.put("贵阳", "Kweiyang");
        CITY_ENGLISH_MAP.put("云南", "Yünnan");
        CITY_ENGLISH_MAP.put("大理", "Tali");
        CITY_ENGLISH_MAP.put("昭通", "Chaotung");
        CITY_ENGLISH_MAP.put("广西", "Kwangsi");
        CITY_ENGLISH_MAP.put("桂林", "Kweilin");
        CITY_ENGLISH_MAP.put("梧州", "Wuchow");
        CITY_ENGLISH_MAP.put("广东", "Kwangtung");
        CITY_ENGLISH_MAP.put("广州", "Guangzhou");
        CITY_ENGLISH_MAP.put("江门", "Kongmoon");
        CITY_ENGLISH_MAP.put("汕头", "Swatow");
        CITY_ENGLISH_MAP.put("嘉应", "Kaying");
        CITY_ENGLISH_MAP.put("顺德", "顺德");
        CITY_ENGLISH_MAP.put("韶州", "Shiuchow");
        CITY_ENGLISH_MAP.put("香港", "HongKong");
        CITY_ENGLISH_MAP.put("九龙", "Kowloong");
        CITY_ENGLISH_MAP.put("福建", "Fukien");
        CITY_ENGLISH_MAP.put("福州", "Foochow");
        CITY_ENGLISH_MAP.put("汀洲", "Tingchow");
        CITY_ENGLISH_MAP.put("厦门", "Amoy");
        CITY_ENGLISH_MAP.put("金门", "Quemoy");
        CITY_ENGLISH_MAP.put("马祖", "Matsu");
        CITY_ENGLISH_MAP.put("台湾", "Taiwan");
        CITY_ENGLISH_MAP.put("台北", "Taipei");
        CITY_ENGLISH_MAP.put("台中", "Taichung");
        CITY_ENGLISH_MAP.put("基隆", "Keelung");
        CITY_ENGLISH_MAP.put("高雄", "Kaohsiung");
        CITY_ENGLISH_MAP.put("左营", "Juo In");
        CITY_ENGLISH_MAP.put("澎湖列岛", "Penghu Liehtao");
        CITY_ENGLISH_MAP.put("花莲", "Hualien");
        CITY_ENGLISH_MAP.put("新竹", "Hsinchu");
        CITY_ENGLISH_MAP.put("嘉义", "Chia’i");
        CITY_ENGLISH_MAP.put("南沙", "Spratly Is");
        CITY_ENGLISH_MAP.put("鹅銮鼻", "Shansi");
        CITY_ENGLISH_MAP.put("太原", "Taiyüan");
        CITY_ENGLISH_MAP.put("大同", "Tatung");
        CITY_ENGLISH_MAP.put("洪洞", "Hungtung");
        CITY_ENGLISH_MAP.put("朔州", "Shohchow");
        CITY_ENGLISH_MAP.put("榆次", "Yütze");
        CITY_ENGLISH_MAP.put("潞安", "Lu’an");
        CITY_ENGLISH_MAP.put("绛州", "Kiangchow");
        CITY_ENGLISH_MAP.put("陕西", "Shensi");
        CITY_ENGLISH_MAP.put("西安", "Si’an");
        CITY_ENGLISH_MAP.put("凤翔", "Fengsiang");
        CITY_ENGLISH_MAP.put("汉中", "Hanchung");
        CITY_ENGLISH_MAP.put("延安", "Yenan");
        CITY_ENGLISH_MAP.put("周至", "Chowchich");
        CITY_ENGLISH_MAP.put("临潼", "Lintung");
        CITY_ENGLISH_MAP.put("同州", "Tungchow");
        CITY_ENGLISH_MAP.put("长安", "Chang’an");
        CITY_ENGLISH_MAP.put("秦州", "Tsinchow");
        CITY_ENGLISH_MAP.put("宁夏", "Ningsia");
        CITY_ENGLISH_MAP.put("甘肃", "Kansu");
        CITY_ENGLISH_MAP.put("兰州", "Lanchow");
        CITY_ENGLISH_MAP.put("河北", "Hopei");
        CITY_ENGLISH_MAP.put("保定", "Paoting");
        CITY_ENGLISH_MAP.put("大名", "Taming");
        CITY_ENGLISH_MAP.put("景县", "Kinghsien");
        CITY_ENGLISH_MAP.put("献县", "Sienhsien");
        CITY_ENGLISH_MAP.put("卢龙", "LuLung");
        CITY_ENGLISH_MAP.put("赵县", "Chaohsien");
        CITY_ENGLISH_MAP.put("正定", "Chengting");
        CITY_ENGLISH_MAP.put("易县", "Yihsien");
    }

    public static String getCityEnglishName(String city) {
        String str = CITY_ENGLISH_MAP.get(city);
        return str == null ? city : str;
    }
}
